FROM node:22-alpine

ARG NEXT_PUBLIC_APIKEY
ARG NEXT_PUBLIC_AUTHDOMAIN
ARG NEXT_PUBLIC_PROJECTID
ARG NEXT_PUBLIC_STORAGEBUCKET
ARG NEXT_PUBLIC_MESSAGINGSENDERID
ARG NEXT_PUBLIC_APPID
ARG DATABASE_URL
ARG GCP_SERVICE_ACCOUNT_PROJECT_ID
ARG GCP_SERVICE_ACCOUNT_PRIVATE_KEY
ARG GCP_SERVICE_ACCOUNT_CLIENT_EMAIL

ENV NEXT_PUBLIC_APIKEY=$NEXT_PUBLIC_APIKEY
ENV NEXT_PUBLIC_AUTHDOMAIN=$NEXT_PUBLIC_AUTHDOMAIN
ENV NEXT_PUBLIC_PROJECTID=$NEXT_PUBLIC_PROJECTID
ENV NEXT_PUBLIC_STORAGEBUCKET=$NEXT_PUBLIC_STORAGEBUCKET
ENV NEXT_PUBLIC_MESSAGINGSENDERID=$NEXT_PUBLIC_MESSAGINGSENDERID
ENV NEXT_PUBLIC_APPID=$NEXT_PUBLIC_APPID
ENV DATABASE_URL=$DATABASE_URL
ENV GCP_SERVICE_ACCOUNT_PROJECT_ID=$GCP_SERVICE_ACCOUNT_PROJECT_ID
ENV GCP_SERVICE_ACCOUNT_PRIVATE_KEY=$GCP_SERVICE_ACCOUNT_PRIVATE_KEY
ENV GCP_SERVICE_ACCOUNT_CLIENT_EMAIL=$GCP_SERVICE_ACCOUNT_CLIENT_EMAIL

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

# dockerに./start.shの実行権限を付与する
RUN chmod +x ./start.sh
# shellスクリプトの実行
CMD ["./start.sh"] 
